# Generated by Django 3.0.6 on 2020-06-11 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tickets_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='approvers',
            field=models.ManyToManyField(related_name='tickets_for_approval', through='django_tickets_2.Approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
