# Generated by Django 3.0.6 on 2020-06-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tickets_2', '0002_auto_20200611_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='user',
            new_name='approver',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.AlterField(
            model_name='approval',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='django_tickets_2.Ticket'),
        ),
    ]
